import course1 from '../images/AcademyCourses/course1.jpg';
import course2 from '../images/AcademyCourses/course2.jpg';
import course3 from '../images/AcademyCourses/course3.jpg';
import course4 from '../images/AcademyCourses/course4.jpg';
const courses = [
    {
        id: '1',
        src: course1,
        name: 'Intensive English Program [IEP]',
        price: '$200',
        duration: '3 weeks',
        hoursPerWeek: '5 hours',
        totalHours: '15 hours',
        description: 'Learning English and becoming a confident communicator in the English language is something that can enrich your life and open up so many new opportunities. This course will help you learn at a pace that is comfortable for you and to motivate you and help you in your journey to learn English!',
        points: ['You will learn to master the basics of English grammar, vocabulary and pronunciation through stimulating and effective content. Practise and test yourself on what you have learnt in the exercises at the end of each lecture.',
            'Each week, we’ll focus on key aspects of English for the workplace. You’ll watch videos and listen to audio recordings of people in various situations.',
            'Assessment will be used as an important tool to check the learning progress on timely basis.',
            'One feedback and doubt clearing session every week with the facilitator for an enriching and productive learning experience.'
        ],
        learn: [
            'You will have a deeper knowledge of the English language as well as its practical application in the different facets of your life. You will no longer be confused about tenses and other grammatical rules',
            'You have gained a comprehensive understanding of the nuances of the English language.',
            'Your reading and writing style will  become sharper and you will be able to apply the strategies you learned to make your communication simple, clear, and effective.',
            'Vocabulary - Emotions, colloquialisms, interests, idioms, personality, social situations, travel,slang, workplace'
        ],
        requirements: [
            'A computer, or a tablet, or a phone with good speakers or headphones. (So you can hear the pronunciation very clearly).',
            'This course is aimed at non-native English speakers who have studied English to at least pre-intermediate level (approximately A2 on the CEFR).',
            '5 hours a week to practice English when you wont be disturbed.',
            'Very positive attitude',
        ],
        objective: [
            'Practice and develop your listening, reading, writing and speaking skills so you can communicate with confidence',
            'Accelerate your confidence level by using English in a wide range of everyday situations.',
            'Building your vocabulary, fluency and accuracy through practical language tasks that focus on real-life situations',
            'Develop your understanding of grammar in context.',

        ],
        topics: [
            'Introducing yourself [ Your Job Profile/ Hobbies/ likes and dislikes/ Daily Routines]',
            'English as a global language [language usage and useful phrases]',
            'Awareness about our communities',
            'Telling the time',
            'Descripting your day/ places around you',
            'Ask and answer questions about personal information',
            'Use a range of verb phrases to talk about common activities',
            'Building vocabulary related to work, food, public places, quantities and qualities etc.',
            'Talking about lifestyle',
            'Enhancing your writing skills by writing paragraphs and letters',
            'Engaging in meaningful conversations',
            'Ordering and giving directions',
            'Joining sentences and giving reasons',
        ],
        eligible: [
            'This course is for people who have a basic knowledge of English and are looking to improve their English language skills.',
            'Enthusiasm and motivation to learn.',
            'This course is for you if English is your second language and believe your career would be better if you improved your communication skills.',
            'This course is for you if you struggle getting your thoughts and words to sync up.',
            'This course is for you if you get nervous or anxious before and during public speaking situations.',
        ],
        teachers: [
            'Ms. Shubhi Tyagi', 'Ms. Monica Verma'
        ],
        iconName: 'hearto'
    },


    {
        id: '2',
        src: course2,
        name: 'PTE Academic Preparation Course [PTE]',
        price: '$250',
        duration: '6 weeks',
        totalHours: '48 hours',
        description: 'The PTE Academic is an approved English Language Testing System for UK, Australian and New Zealand visa and immigration categories.The PTE Academic is split into three parts. There are 20 different question types in the test, ranging from multiple choice through to essay writing. The speaking and writing are combined, whilst the reading and listening are stand alone segments. The PTE Academic test will be conducted online. The students that wish to apply for a UK visa will need to undertake the PTE Academic UKVI.',
        points: ['It is a full beginner to intermediate course of spoken English. It is specifically designed to help you build all the necessary skills for real-life day-to-day use.',
        'You get over 40 hours of English language practice. Each English language lesson lasts about 1 hour.',
        'It is 100% communicative intensive spoken English language course. You speak English language all the time and you say approx. 2000 English words in each lesson.',
        'English grammar is explained in an extremely simple and intuitive way, with tons of examples and many hours of listening and speaking practice.',
        'Assessment will be used as an important tool to check the learning progress on timely basis.',
        'One feedback and doubt clearing session every week with the facilitator for an enriching and productive learning experience.'],
        goal: 'At the end of this course, students should have been provided the knowledge and practice to achieve a minimum score of 36 on the PTE Academic Test.',
        objective: [
            'Can understand the overall meaning of simple, extended texts on familiar concrete topics and some unfamiliar concrete topics',
            'Can speak coherently in extended exchanges using basic repair strategies to maintain the flow of communication',
            'Can write simple, extended texts on familiar and concrete topics',
            'Understand the overall meaning of simple, extended texts on familiar and some unfamiliar topics',
            'Identify specific information in simple, extended texts on familiar and some unfamiliar topics.',
            'Make predictions when listening to simple, extended texts on familiar and some unfamiliar topics',
            'Identify a range of features of text organization and structure',
            'Read and understand the overall meaning of simple, extended texts on familiar and some unfamiliar concreate topics',
            'Infer the meaning of unknown words when reading texts on familiar concrete topics',
            'Produce connected speech using correct intonation and rhythm',
            'Speak coherently in extended exchanges using basic repair strategies to maintain the flow of communication.',
            'Make predictions when reading simple extended texts on familiar and concrete topics.',
            'Express own ideas and respond to the ideas of others.',
            'Use simple and complex language structures in writing',
            'Paraphrase and synthesize information from a variety of sources',
            'Write structured paragraphs that contain a topic sentence and supporting details',

        ],
        topics: [
            'You and your hometown',
            'Places population & architecture',
            'Education & Employment',
            'Food, drink, culture and fashion',
            'Health care and lifestyle',
            'Technology and the internet',
        ],
        eligible: [
            'Understand the main point in short, clear, simple messages and announcements.',
            'Identify specific information in simple, extended texts on familiar topics.',
            'Understand common phrases and high frequency vocabulary related to regularly encountered topics (work, family, study, leisure)',
            'Recognize key features of text organization',
            'Read texts on unfamiliar and concrete topics',
            'Find specific, predictable information and understand descriptions of feelings and intentions.',
            'Make predictions when reading simple texts.',
            'Communicate in simple and direct exchanges of information on familiar topics (family, work, leisure).',
            'Use a range of basic language structures when speaking',
            'Connect phrases and sentences in simple ways to describe experiences, events, feelings and ambitions.',
            'Initiate and participate in a range of interactions on familiar and concrete topics',
            'Write a series of simple phrases and sentences linked with simple connectors on familiar topics (work, family, personal interest)',
            'Use own and others’ ideas and develop ideas before writing',
            'Write simple personal letters describing experiences and feelings',
        ],
        teachers: [
            'Richard Westmacott'
        ],
        iconName: 'hearto'
    },


    {
        id: '3',
        src: course3,
        name: 'Foundation IELTS English Course [FIEC]',
        price: '$180',
        duration: '7 weeks',
        totalHours: '56 hours',
        description: 'IELTS is the world’s leading English language test for migration and higher education. IELTS is designed to test the language ability of people who want to study or work where English is used as the language of communication. In IELTS, there are four papers: Listening, Reading, Writing and Speaking. There are two different IELTS modules: Academic and General Training. The Speaking and Listening tests are the same in both modules, but the Reading and Writing tests are different. The students put forward by XA Group as part of the Skilled Migration Program will be completing the IELTS General assessments.',
        points: ['It is a full beginner to intermediate course of spoken English. It is specifically designed to help you build all the necessary skills for real-life day-to-day use.',
        'You get over 40 hours of English language practice. Each English language lesson lasts about 1 hour.',
        'It is 100% communicative intensive spoken English language course. You speak English language all the time and you say approx. 2000 English words in each lesson.',
        'English grammar is explained in an extremely simple and intuitive way, with tons of examples and many hours of listening and speaking practice.',
        'Assessment will be used as an important tool to check the learning progress on timely basis.',
        'One feedback and doubt clearing session every week with the facilitator for an enriching and productive learning experience.'],
        goal: 'At the end of this course, students should have been provided the knowledge and practice to achieve a minimum of an IELTS band 5.',
        objective: [
            'Practice and develop your listening, reading, writing and speaking skills so you can communicate with confidenc',
            'Accelerate your confidence level by using English in a wide range of everyday situations.',
            'Building your vocabulary, fluency and accuracy through practical language tasks that focus on real-life situations',
            'Develop your understanding of grammar in context.',
            'Understand the overall meaning of extended texts on familiar and unfamiliar concrete topics',
            'Identify details in extended texts on familiar topics',
            'Make predictions when listening to simple extended texts on familiar topics',
            'Recognize speaker’s attitude in simple texts on familiar and concrete topics',
            'Read and understand the overall meaning of simple extended texts on familiar topics',
            'Identify the main points in simple extended texts on familiar topics.',
            'Infer meaning when reading simple texts on familiar and unfamiliar concrete topics.',
            'Make predictions when reading simple extended texts on familiar and concrete topics.',
            'Produce connected speech using correct intonation and rhythm',
            'Speak coherently in extended exchanges using basic repair strategies to maintain flow of communication',
            'Express own ideas and respond to the ideas of others',
            'Use simple and complex language structures in writing',
            'Paraphrase and synthesize information from a variety of sources',
            'Write structured paragraphs that contain a topic sentence and supporting details',

        ],
        topics: [
            'Discuss the topic of hometowns',
            'Introduce yourself in a conversation',
            'Practice skimming a text and speed reading',
            'Understand the listening context',
            'Improve vocabulary related to locations and buildings',
            'Understand longer pieces of text and multiple texts.',
            'Practice T/F/NG questions and writing summaries',
            'Develop informal, semi-formal and formal writing skills',
            'Recognize paraphrasing and sentence completion',
            'Understand the concept of writing letters',
            'Talk about familiar topics and using booklets as speaking prompts',
            'Discuss student life and studying',
            'Identifying theories and opinions in discursive passages',
            'Learn how to check and correct common writing errors',
            'Develop understanding of descriptions of places and directions',
            'Learn how to talk about abstract topics',
            'Expand vocabulary related to trends and culture',
            'Identify types of information and learn how to locate and connect ideas',
            'Learn how to plan and organize ideas in writing',
            'Understand mechanical parts and vocabulary – diagram labelling',
            'Develop fluency and coherence in speaking',
            'Discuss job roles, companies and employment',
            'Learn how to distinguish the main ideas from supporting ideas',
            'Understand how to link ideas and express personal views',
            'Identifying varying attitudes and opinions in speech',
            'Develop grammatical range and accuracy in speaking',
            'Talk about changes and trends in technology and hobbies',
            'Identify theories and opinion in texts',
            'Learn how to develop ideas clearly and improve grammatical accuracy',
            'Develop skills in following a lecture or talk – connect ideas',
            'Improve pronunciation and intonation',
            'Discuss environmental topics',
            'Learn how to deal with argumentative texts and views',
            'Improve punctuation use and assess language level',
            'Identify contrasts and comparisons',
            'Expand vocabulary and improve lexical score',
        ],
        eligible: [
            'Understand the main point in short, clear, simple messages and announcements.',
            'Identify specific information in simple, extended texts on familiar topics.',
            'Understand common phrases and high frequency vocabulary related to regularly encountered topics (work, family, study, leisure)',
            'Recognize key features of text organization',
            'Read texts on unfamiliar and concrete topics',
            'Find specific, predictable information and understand descriptions of feelings and intentions.',
            'Make predictions when reading simple texts.',
            'Communicate in simple and direct exchanges of information on familiar topics (family, work, leisure).',
            'Use a range of basic language structures when speaking',
            'Connect phrases and sentences in simple ways to describe experiences, events, feelings and ambitions.',
            'Initiate and participate in a range of interactions on familiar and concrete topics',
            'Write a series of simple phrases and sentences linked with simple connectors on familiar topics (work, family, personal interest)',
            'Use own and others’ ideas and develop ideas before writing',
            'Write simple personal letters describing experiences and feelings',
        ],
        teachers: [
            'Richard Westmacott'
        ],
        iconName: 'hearto'
    },


    {
        id: '4',
        src: course4,
        name: 'Extensive English Program [EEP]',
        price: '$100',
        duration: '8 weeks',
        hoursPerWeek: '5 hours',
        totalHours: '40 hours',
        description: 'It is a must-have English language course for complete beginners in English, who want to reach the intermediate level of spoken English language in the shortest time possible.',
        points: ['It is a full beginner to intermediate course of spoken English. It is specifically designed to help you build all the necessary skills for real-life day-to-day use.',
        'You get over 40 hours of English language practice. Each English language lesson lasts about 1 hour.',
        'It is 100% communicative intensive spoken English language course. You speak English language all the time and you say approx. 2000 English words in each lesson.',
        'English grammar is explained in an extremely simple and intuitive way, with tons of examples and many hours of listening and speaking practice.',
        'Assessment will be used as an important tool to check the learning progress on timely basis.',
        'One feedback and doubt clearing session every week with the facilitator for an enriching and productive learning experience.'],
        learn: ['Learn to speak more fluently so that both you and those to whom you are speaking feel connected and can exchange information.',
                'Develop their writing skills by giving description of people, places and things and respond imaginatively to textual questions',
                'Learn to understand and apply content/academic vocabulary critical to the meaning of the text, including vocabularies relevant to different contexts, cultures, and communities.',
                'Learn to enhance their listening skills by relating what you hear to what you read in coherent writing and speech.',
        ],
        requirements: [
            'A computer, or a tablet, or a phone with good speakers or headphones. (So you can hear the pronunciation very clearly).',
            'This course is aimed at non-native English speakers who have studied English to at least pre-intermediate level (approximately A1 on the CEFR).',
            '5 hours a week to practice English when you wont be disturbed.',
            'Very positive attitude',
        ],
        objective: [
            'Can understand the overall meaning of complex texts on familiar and unfamiliar concrete topics.',
            'Can maintain flow of communication using a range of repair strategies',
            'Building your vocabulary, fluency and accuracy through practical language tasks that focus on real-life situations.',
            'Can produce clear, detailed text on familiar and some unfamiliar concrete topics.',
        ],
        topics: [
            'Make Interactions and say goodbye',
            'Talking about your Job Profile/ Hobbies/ likes and dislikes/ Daily Routines]',
            'English as a global language [language usage and useful phrases]',
            'Understanding and say countries of the world and nationalities',
            'Use possessive adjectives in sentences like my, your, his',
            'Use a range of vocabulary to talk about common objects',
            'Form simple sentences using the possessives',
            'Awareness about our communities',
            'Descripting your day/ places around you',
            'Developing art of asking questions',
            'Building vocabulary related to work, food, public places, quantities and qualities etc.',
            'Talking about lifestyle',
            'Crafting the perfect story',
            'Engaging in meaningful conversations',
            'Ordering and giving directions',
            'Joining sentences',
            'Giving reasons',
        ],
        eligible: [
            'This course is for non-native English speakers who have a little or no knowledge about the English language (approximately A1 on the CEFR).',
            'This course is for you if you struggle getting your thoughts and words to sync up.',
            'This course is for you if you get nervous or anxious before and during public speaking situations.',
        ],
       
        teachers: [
            'Ms. Shubhi Tyagi', 'Ms. Monica Verma'
        ],
        iconName: 'hearto'
    },

]
export function getCourses() {
    return courses;
}
export function getCourse(id) {
    return courses.find((course) => (course.id == id));
}
export default courses;